module.exports = [
  {
    city: 'London',
    admin: '',
    country: 'United Kingdom',
    population_proper: '7421209',
    iso2: 'GB',
    capital: 'primary',
    lat: '51.514248',
    lng: '-0.093145',
    population: '8567000',
  },
  {
    city: 'Birmingham',
    admin: 'Birmingham',
    country: 'United Kingdom',
    population_proper: '984333',
    iso2: 'GB',
    capital: 'admin',
    lat: '52.466667',
    lng: '-1.916667',
    population: '2285000',
  },
  {
    city: 'Manchester',
    admin: 'Manchester',
    country: 'United Kingdom',
    population_proper: '395515',
    iso2: 'GB',
    capital: 'admin',
    lat: '53.5',
    lng: '-2.216667',
    population: '2230000',
  },
  {
    city: 'Leeds',
    admin: 'Leeds',
    country: 'United Kingdom',
    population_proper: '455123',
    iso2: 'GB',
    capital: 'admin',
    lat: '53.8',
    lng: '-1.583333',
    population: '1529000',
  },
  {
    city: 'Sheffield',
    admin: 'Sheffield',
    country: 'United Kingdom',
    population_proper: '552700',
    iso2: 'GB',
    capital: 'admin',
    lat: '53.366667',
    lng: '-1.5',
    population: '1292900',
  },
  {
    city: 'Glasgow',
    admin: 'Glasgow City',
    country: 'United Kingdom',
    population_proper: '610268',
    iso2: 'GB',
    capital: 'admin',
    lat: '55.833333',
    lng: '-4.25',
    population: '1160000',
  },
  {
    city: 'Newcastle upon Tyne',
    admin: 'Newcastle upon Tyne',
    country: 'United Kingdom',
    population_proper: '192382',
    iso2: 'GB',
    capital: 'admin',
    lat: '54.988056',
    lng: '-1.619444',
    population: '882000',
  },
  {
    city: 'Nottingham',
    admin: 'Nottingham',
    country: 'United Kingdom',
    population_proper: '305700',
    iso2: 'GB',
    capital: 'admin',
    lat: '52.966667',
    lng: '-1.166667',
    population: '825600',
  },
  {
    city: 'Liverpool',
    admin: 'Liverpool',
    country: 'United Kingdom',
    population_proper: '468945',
    iso2: 'GB',
    capital: 'admin',
    lat: '53.416667',
    lng: '-3.0',
    population: '811000',
  },
  {
    city: 'Southend-on-Sea',
    admin: 'Southend-on-Sea',
    country: 'United Kingdom',
    population_proper: '173600',
    iso2: 'GB',
    capital: 'admin',
    lat: '51.533333',
    lng: '0.7',
    population: '618386',
  },
  {
    city: 'Bristol',
    admin: 'Bristol, City of',
    country: 'United Kingdom',
    population_proper: '430713',
    iso2: 'GB',
    capital: 'admin',
    lat: '51.45',
    lng: '-2.583333',
    population: '553528',
  },
  {
    city: 'Edinburgh',
    admin: 'Edinburgh, City of',
    country: 'United Kingdom',
    population_proper: '435791',
    iso2: 'GB',
    capital: 'admin',
    lat: '55.95',
    lng: '-3.2',
    population: '504966',
  },
  {
    city: 'Brighton',
    admin: 'Brighton and Hove',
    country: 'United Kingdom',
    population_proper: '139001',
    iso2: 'GB',
    capital: '',
    lat: '50.833333',
    lng: '-0.15',
    population: '503008',
  },
  {
    city: 'Bradford',
    admin: 'Bradford',
    country: 'United Kingdom',
    population_proper: '293717',
    iso2: 'GB',
    capital: 'admin',
    lat: '53.783333',
    lng: '-1.75',
    population: '501700',
  },
  {
    city: 'Leicester',
    admin: 'Leicester',
    country: 'United Kingdom',
    population_proper: '339239',
    iso2: 'GB',
    capital: 'admin',
    lat: '52.633333',
    lng: '-1.133333',
    population: '457983',
  },
  {
    city: 'Sunderland',
    admin: 'Sunderland',
    country: 'United Kingdom',
    population_proper: '177965',
    iso2: 'GB',
    capital: 'admin',
    lat: '54.911944',
    lng: '-1.383333',
    population: '452934',
  },
  {
    city: 'Belfast',
    admin: 'Belfast',
    country: 'United Kingdom',
    population_proper: '274770',
    iso2: 'GB',
    capital: '',
    lat: '54.6',
    lng: '-5.933333',
    population: '450406',
  },
  {
    city: 'Portsmouth',
    admin: 'Portsmouth',
    country: 'United Kingdom',
    population_proper: '205100',
    iso2: 'GB',
    capital: 'admin',
    lat: '50.766667',
    lng: '-1.083333',
    population: '442252',
  },
  {
    city: 'Bournemouth',
    admin: 'Bournemouth',
    country: 'United Kingdom',
    population_proper: '163600',
    iso2: 'GB',
    capital: 'admin',
    lat: '50.716667',
    lng: '-1.883333',
    population: '426945',
  },
  {
    city: 'Middlesbrough',
    admin: 'Redcar and Cleveland',
    country: 'United Kingdom',
    population_proper: '142707',
    iso2: 'GB',
    capital: 'admin',
    lat: '54.572778',
    lng: '-1.162778',
    population: '416042',
  },
  {
    city: 'Coventry',
    admin: 'Coventry',
    country: 'United Kingdom',
    population_proper: '308313',
    iso2: 'GB',
    capital: 'admin',
    lat: '52.416667',
    lng: '-1.55',
    population: '388271',
  },
  {
    city: 'Southampton',
    admin: 'Southampton',
    country: 'United Kingdom',
    population_proper: '384417',
    iso2: 'GB',
    capital: 'admin',
    lat: '50.9',
    lng: '-1.4',
    population: '384417',
  },
  {
    city: 'Reading',
    admin: 'Reading',
    country: 'United Kingdom',
    population_proper: '145700',
    iso2: 'GB',
    capital: 'admin',
    lat: '51.433333',
    lng: '-1.0',
    population: '369804',
  },
  {
    city: 'Sutton on Hull',
    admin: 'Kingston upon Hull, City of',
    country: 'United Kingdom',
    population_proper: '292501',
    iso2: 'GB',
    capital: '',
    lat: '53.783333',
    lng: '-0.316667',
    population: '302296',
  },
  {
    city: 'Blackpool',
    admin: 'Blackpool',
    country: 'United Kingdom',
    population_proper: '143101',
    iso2: 'GB',
    capital: 'admin',
    lat: '53.816667',
    lng: '-3.05',
    population: '272792',
  },
  {
    city: 'Plymouth',
    admin: 'Plymouth',
    country: 'United Kingdom',
    population_proper: '231575',
    iso2: 'GB',
    capital: 'admin',
    lat: '50.396389',
    lng: '-4.138611',
    population: '247297',
  },
  {
    city: 'Luton',
    admin: 'Luton',
    country: 'United Kingdom',
    population_proper: '193669',
    iso2: 'GB',
    capital: 'admin',
    lat: '51.883333',
    lng: '-0.416667',
    population: '235958',
  },
  {
    city: 'Oxford',
    admin: 'Oxfordshire',
    country: 'United Kingdom',
    population_proper: '154566',
    iso2: 'GB',
    capital: 'admin',
    lat: '51.75',
    lng: '-1.25',
    population: '192796',
  },
  {
    city: 'Norwich',
    admin: 'Norfolk',
    country: 'United Kingdom',
    population_proper: '177636',
    iso2: 'GB',
    capital: 'admin',
    lat: '52.633333',
    lng: '1.3',
    population: '190756',
  },
  {
    city: 'Old Aberdeen',
    admin: 'Aberdeen City',
    country: 'United Kingdom',
    population_proper: '183790',
    iso2: 'GB',
    capital: '',
    lat: '57.166667',
    lng: '-2.1',
    population: '189364',
  },
  {
    city: 'York',
    admin: 'York',
    country: 'United Kingdom',
    population_proper: '144202',
    iso2: 'GB',
    capital: 'admin',
    lat: '53.966667',
    lng: '-1.083333',
    population: '158947',
  },
  {
    city: 'Dundee',
    admin: 'Dundee City',
    country: 'United Kingdom',
    population_proper: '150435',
    iso2: 'GB',
    capital: 'admin',
    lat: '56.5',
    lng: '-2.966667',
    population: '151592',
  },
  {
    city: 'Ipswich',
    admin: 'Suffolk',
    country: 'United Kingdom',
    population_proper: '134257',
    iso2: 'GB',
    capital: 'admin',
    lat: '52.083333',
    lng: '1.166667',
    population: '143767',
  },
  {
    city: 'Peterborough',
    admin: 'Peterborough',
    country: 'United Kingdom',
    population_proper: '140141',
    iso2: 'GB',
    capital: 'admin',
    lat: '52.583333',
    lng: '-0.25',
    population: '140141',
  },
  {
    city: 'Cambridge',
    admin: 'Cambridgeshire',
    country: 'United Kingdom',
    population_proper: '128488',
    iso2: 'GB',
    capital: 'admin',
    lat: '52.2',
    lng: '0.116667',
    population: '128488',
  },
  {
    city: 'Exminster',
    admin: 'Devon',
    country: 'United Kingdom',
    population_proper: '103366',
    iso2: 'GB',
    capital: '',
    lat: '50.683333',
    lng: '-3.483333',
    population: '113118',
  },
  {
    city: 'Bath',
    admin: 'Bath and North East Somerset',
    country: 'United Kingdom',
    population_proper: '92120',
    iso2: 'GB',
    capital: 'admin',
    lat: '51.379444',
    lng: '-2.365556',
    population: '93238',
  },
  {
    city: 'Chester',
    admin: 'Cheshire West and Chester',
    country: 'United Kingdom',
    population_proper: '77040',
    iso2: 'GB',
    capital: 'admin',
    lat: '53.2',
    lng: '-2.916667',
    population: '89531',
  },
  {
    city: 'Greenock',
    admin: 'Inverclyde',
    country: 'United Kingdom',
    population_proper: '43495',
    iso2: 'GB',
    capital: 'admin',
    lat: '55.933333',
    lng: '-4.75',
    population: '74635',
  },
  {
    city: 'Carlisle',
    admin: 'Cumbria',
    country: 'United Kingdom',
    population_proper: '65907',
    iso2: 'GB',
    capital: 'admin',
    lat: '54.883333',
    lng: '-2.933333',
    population: '72633',
  },
  {
    city: 'Scarborough',
    admin: 'North Yorkshire',
    country: 'United Kingdom',
    population_proper: '70571',
    iso2: 'GB',
    capital: '',
    lat: '54.287222',
    lng: '-0.414167',
    population: '70571',
  },
  {
    city: 'Ayr',
    admin: 'South Ayrshire',
    country: 'United Kingdom',
    population_proper: '45513',
    iso2: 'GB',
    capital: 'admin',
    lat: '55.45',
    lng: '-4.616667',
    population: '69042',
  },
  {
    city: 'Inverness',
    admin: 'Highland',
    country: 'United Kingdom',
    population_proper: '40755',
    iso2: 'GB',
    capital: 'admin',
    lat: '57.466667',
    lng: '-4.233333',
    population: '45158',
  },
  {
    city: 'Perth',
    admin: 'Perth and Kinross',
    country: 'United Kingdom',
    population_proper: '39654',
    iso2: 'GB',
    capital: 'admin',
    lat: '56.4',
    lng: '-3.433333',
    population: '39654',
  },
  {
    city: 'River',
    admin: 'Kent',
    country: 'United Kingdom',
    population_proper: '28156',
    iso2: 'GB',
    capital: '',
    lat: '51.133333',
    lng: '1.266667',
    population: '36384',
  },
  {
    city: 'Dumfries',
    admin: 'Dumfries and Galloway',
    country: 'United Kingdom',
    population_proper: '31044',
    iso2: 'GB',
    capital: 'admin',
    lat: '55.066667',
    lng: '-3.55',
    population: '31044',
  },
  {
    city: 'Omagh',
    admin: 'Fermanagh and Omagh',
    country: 'United Kingdom',
    population_proper: '16326',
    iso2: 'GB',
    capital: 'admin',
    lat: '54.60124',
    lng: '-7.29085',
    population: '21056',
  },
  {
    city: 'Penzance',
    admin: 'Cornwall',
    country: 'United Kingdom',
    population_proper: '15489',
    iso2: 'GB',
    capital: '',
    lat: '50.113611',
    lng: '-5.547778',
    population: '20812',
  },
  {
    city: 'Fort William',
    admin: 'Highland',
    country: 'United Kingdom',
    population_proper: '9652',
    iso2: 'GB',
    capital: '',
    lat: '56.816667',
    lng: '-5.116667',
    population: '9652',
  },
  {
    city: 'Kirkwall',
    admin: 'Orkney Islands',
    country: 'United Kingdom',
    population_proper: '3153',
    iso2: 'GB',
    capital: 'admin',
    lat: '58.966667',
    lng: '-2.95',
    population: '8500',
  },
  {
    city: 'Wick',
    admin: 'Highland',
    country: 'United Kingdom',
    population_proper: '7147',
    iso2: 'GB',
    capital: '',
    lat: '58.433333',
    lng: '-3.083333',
    population: '7147',
  },
  {
    city: 'Lerwick',
    admin: 'Shetland Islands',
    country: 'United Kingdom',
    population_proper: '4614',
    iso2: 'GB',
    capital: 'admin',
    lat: '60.15',
    lng: '-1.15',
    population: '6594',
  },
  {
    city: 'Ilford',
    admin: 'Redbridge',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '51.559666',
    lng: '0.070805',
    population: '',
  },
  {
    city: 'Chelmsford',
    admin: 'Essex',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '51.733333',
    lng: '0.483333',
    population: '',
  },
  {
    city: 'Weston-super-Mare',
    admin: 'North Somerset',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '51.345833',
    lng: '-2.967778',
    population: '',
  },
  {
    city: 'Llangefni',
    admin: 'Isle of Anglesey',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '53.266667',
    lng: '-4.333333',
    population: '',
  },
  {
    city: 'Southport',
    admin: 'Sefton',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '53.666667',
    lng: '-3.0',
    population: '',
  },
  {
    city: 'Armagh',
    admin: 'Armagh, Banbridge and Craigavon',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '54.34812',
    lng: '-6.64957',
    population: '',
  },
  {
    city: 'Rochester',
    admin: 'Medway',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '51.383333',
    lng: '0.516667',
    population: '',
  },
  {
    city: 'Rochdale',
    admin: 'Rochdale',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '53.616667',
    lng: '-2.15',
    population: '',
  },
  {
    city: 'Motherwell',
    admin: 'North Lanarkshire',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '55.783333',
    lng: '-4.0',
    population: '',
  },
  {
    city: 'Clydach Vale',
    admin: 'Rhondda Cynon Taff',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '51.626667',
    lng: '-3.476111',
    population: '',
  },
  {
    city: 'Kirkintilloch',
    admin: 'East Dunbartonshire',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '55.916667',
    lng: '-4.166667',
    population: '',
  },
  {
    city: 'Stirling',
    admin: 'Stirling',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '56.116667',
    lng: '-3.95',
    population: '',
  },
  {
    city: 'Lambeth',
    admin: 'Lambeth',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '51.5',
    lng: '-0.116667',
    population: '',
  },
  {
    city: 'Dungannon',
    admin: 'Mid Ulster',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '54.50333',
    lng: '-6.76427',
    population: '',
  },
  {
    city: 'Huddersfield',
    admin: 'Kirklees',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '53.65',
    lng: '-1.783333',
    population: '',
  },
  {
    city: 'Stretford',
    admin: 'Trafford',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '53.45',
    lng: '-2.316667',
    population: '',
  },
  {
    city: 'Preston',
    admin: 'Lancashire',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '53.766667',
    lng: '-2.716667',
    population: '',
  },
  {
    city: 'Newbury',
    admin: 'West Berkshire',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '51.4',
    lng: '-1.316667',
    population: '',
  },
  {
    city: 'Rhuthun',
    admin: 'Denbighshire',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '53.116667',
    lng: '-3.3',
    population: '',
  },
  {
    city: 'Blackburn',
    admin: 'Blackburn with Darwen',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '53.75',
    lng: '-2.483333',
    population: '',
  },
  {
    city: 'Wood Green',
    admin: 'Haringey',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '51.6',
    lng: '-0.116667',
    population: '',
  },
  {
    city: 'Stafford',
    admin: 'St. Helens',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '52.8',
    lng: '-2.1',
    population: '',
  },
  {
    city: 'Gloucester',
    admin: 'Gloucestershire',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '51.833333',
    lng: '-2.25',
    population: '',
  },
  {
    city: 'Glenrothes',
    admin: 'Fife',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '56.2',
    lng: '-3.183333',
    population: '',
  },
  {
    city: 'South Bank',
    admin: 'Redcar and Cleveland',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '54.566667',
    lng: '-1.15',
    population: '',
  },
  {
    city: 'Pont-y-pŵl',
    admin: 'Torfaen',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '51.701111',
    lng: '-3.044444',
    population: '',
  },
  {
    city: 'Durham',
    admin: 'Durham',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '54.766667',
    lng: '-1.566667',
    population: '',
  },
  {
    city: 'Bedford',
    admin: 'Bedford',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '52.133333',
    lng: '-0.45',
    population: '',
  },
  {
    city: 'Taunton',
    admin: 'Somerset',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '51.021111',
    lng: '-3.104722',
    population: '',
  },
  {
    city: 'Widnes',
    admin: 'Halton',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '53.35',
    lng: '-2.733333',
    population: '',
  },
  {
    city: 'Uxbridge',
    admin: 'Hillingdon',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '51.55',
    lng: '-0.483333',
    population: '',
  },
  {
    city: 'Elgin',
    admin: 'Moray',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '57.65',
    lng: '-3.333333',
    population: '',
  },
  {
    city: 'Hove',
    admin: 'Brighton and Hove',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '50.833333',
    lng: '-0.183333',
    population: '',
  },
  {
    city: 'Lewes',
    admin: 'East Sussex',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '50.866667',
    lng: '-0.016667',
    population: '',
  },
  {
    city: 'Maidstone',
    admin: 'Kent',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '51.266667',
    lng: '0.516667',
    population: '',
  },
  {
    city: 'Llandrindod Wells',
    admin: 'Powys',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '52.233333',
    lng: '-3.383333',
    population: '',
  },
  {
    city: 'Kingston upon Hull',
    admin: 'Kingston upon Hull, City of',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '53.716667',
    lng: '-0.333333',
    population: '',
  },
  {
    city: 'Kingston upon Thames',
    admin: 'Kingston upon Thames',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '51.416667',
    lng: '-0.283333',
    population: '',
  },
  {
    city: 'Barri',
    admin: 'Vale of Glamorgan, The',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '51.406667',
    lng: '-3.269444',
    population: '',
  },
  {
    city: 'Giffnock',
    admin: 'East Renfrewshire',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '55.8',
    lng: '-4.283333',
    population: '',
  },
  {
    city: 'Hounslow',
    admin: 'Hounslow',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '51.466667',
    lng: '-0.35',
    population: '',
  },
  {
    city: 'Derry',
    admin: 'Derry and Strabane',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '54.99899',
    lng: '-7.31063',
    population: '',
  },
  {
    city: 'Newtownabbey',
    admin: 'Antrim and Newtownabbey',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '54.66912',
    lng: '-5.904435',
    population: '',
  },
  {
    city: 'Forfar',
    admin: 'Angus',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '56.65',
    lng: '-2.883333',
    population: '',
  },
  {
    city: 'Torquay',
    admin: 'Torbay',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '50.45',
    lng: '-3.5',
    population: '',
  },
  {
    city: 'East Ham',
    admin: 'Newham',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '51.533333',
    lng: '0.05',
    population: '',
  },
  {
    city: 'Solihull',
    admin: 'Solihull',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '52.416667',
    lng: '-1.783333',
    population: '',
  },
  {
    city: 'Poplar',
    admin: 'Tower Hamlets',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '51.5',
    lng: '-0.016667',
    population: '',
  },
  {
    city: 'Mold',
    admin: 'Flintshire',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '53.166667',
    lng: '-3.133333',
    population: '',
  },
  {
    city: 'Warwick',
    admin: 'Warwickshire',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '52.283333',
    lng: '-1.583333',
    population: '',
  },
  {
    city: 'Knowsley',
    admin: 'Knowsley',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '53.45',
    lng: '-2.85',
    population: '',
  },
  {
    city: 'Hwlffordd',
    admin: 'Pembrokeshire',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '51.801667',
    lng: '-4.970833',
    population: '',
  },
  {
    city: 'Rotherham',
    admin: 'Rotherham',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '53.433333',
    lng: '-1.35',
    population: '',
  },
  {
    city: 'Caernarfon',
    admin: 'Gwynedd',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '53.15',
    lng: '-4.266667',
    population: '',
  },
  {
    city: 'Morpeth',
    admin: 'Northumberland',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '55.166667',
    lng: '-1.683333',
    population: '',
  },
  {
    city: 'Irvine',
    admin: 'North Ayrshire',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '55.6',
    lng: '-4.666667',
    population: '',
  },
  {
    city: 'Cwmbran',
    admin: 'Monmouthshire',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '51.653056',
    lng: '-3.026667',
    population: '',
  },
  {
    city: 'Stornoway',
    admin: 'Eilean Siar',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '58.216667',
    lng: '-6.366667',
    population: '',
  },
  {
    city: 'Darlington',
    admin: 'Darlington',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '54.533333',
    lng: '-1.566667',
    population: '',
  },
  {
    city: 'Hackney',
    admin: 'Hackney',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '51.55',
    lng: '-0.05',
    population: '',
  },
  {
    city: 'Trowbridge',
    admin: 'Wiltshire',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '51.318889',
    lng: '-2.208611',
    population: '',
  },
  {
    city: 'Merthyr Tudful',
    admin: 'Merthyr Tydfil',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '51.75',
    lng: '-3.383333',
    population: '',
  },
  {
    city: 'Hertford',
    admin: 'Hertfordshire',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '51.8',
    lng: '-0.066667',
    population: '',
  },
  {
    city: 'Newry',
    admin: 'Newry, Mourne and Down',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '54.17795',
    lng: '-6.33807',
    population: '',
  },
  {
    city: 'Belfast',
    admin: 'Belfast',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '54.59682',
    lng: '-5.92541',
    population: '',
  },
  {
    city: 'Camberwell',
    admin: 'Southwark',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '51.473619',
    lng: '-0.091618',
    population: '',
  },
  {
    city: 'Caerfyrddin',
    admin: 'Carmarthenshire',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '51.859167',
    lng: '-4.311667',
    population: '',
  },
  {
    city: 'Cookstown',
    admin: 'Mid Ulster',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '54.6428',
    lng: '-6.74519',
    population: '',
  },
  {
    city: 'Dorchester',
    admin: 'Dorset',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '50.716667',
    lng: '-2.433333',
    population: '',
  },
  {
    city: 'Port Talbot',
    admin: 'Neath Port Talbot',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '51.6',
    lng: '-3.783333',
    population: '',
  },
  {
    city: 'Antrim',
    admin: 'Antrim and Newtownabbey',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '54.71291',
    lng: '-6.20846',
    population: '',
  },
  {
    city: 'Gateshead',
    admin: 'Gateshead',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '54.945',
    lng: '-1.6175',
    population: '',
  },
  {
    city: 'Wandsworth',
    admin: 'Wandsworth',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '51.45',
    lng: '-0.2',
    population: '',
  },
  {
    city: 'Exeter',
    admin: 'Devon',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '50.7',
    lng: '-3.533333',
    population: '',
  },
  {
    city: 'Camden Town',
    admin: 'Camden',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '51.545664',
    lng: '-0.140308',
    population: '',
  },
  {
    city: 'Alloa',
    admin: 'Clackmannanshire',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '56.116667',
    lng: '-3.8',
    population: '',
  },
  {
    city: 'Chicksands',
    admin: 'Central Bedfordshire',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '52.033333',
    lng: '-0.366667',
    population: '',
  },
  {
    city: 'Banbridge',
    admin: 'Armagh, Banbridge and Craigavon',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '54.35091',
    lng: '-6.26701',
    population: '',
  },
  {
    city: 'Walthamstow',
    admin: 'Waltham Forest',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '51.6',
    lng: '-0.033333',
    population: '',
  },
  {
    city: 'Paisley',
    admin: 'Renfrewshire',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '55.833333',
    lng: '-4.433333',
    population: '',
  },
  {
    city: 'Chichester',
    admin: 'West Sussex',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '50.833333',
    lng: '-0.783333',
    population: '',
  },
  {
    city: 'Craigavon',
    admin: 'Armagh, Banbridge and Craigavon',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '54.44966',
    lng: '-6.36457',
    population: '',
  },
  {
    city: 'Woolwich',
    admin: 'Greenwich',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '51.466667',
    lng: '0.2',
    population: '',
  },
  {
    city: 'Northallerton',
    admin: 'North Yorkshire',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '54.333333',
    lng: '-1.433333',
    population: '',
  },
  {
    city: 'Romford',
    admin: 'Havering',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '51.583333',
    lng: '0.2',
    population: '',
  },
  {
    city: 'Walsall',
    admin: 'Walsall',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '52.6',
    lng: '-2.0',
    population: '',
  },
  {
    city: 'Scunthorpe',
    admin: 'North Lincolnshire',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '53.583333',
    lng: '-0.65',
    population: '',
  },
  {
    city: 'Islington',
    admin: 'Islington',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '51.533333',
    lng: '-0.1',
    population: '',
  },
  {
    city: 'Oldbury',
    admin: 'Sandwell',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '52.5',
    lng: '-2.016667',
    population: '',
  },
  {
    city: 'Downpatrick',
    admin: 'Newry, Mourne and Down',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '54.32694',
    lng: '-5.71134',
    population: '',
  },
  {
    city: 'Livingston',
    admin: 'West Lothian',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '55.883333',
    lng: '-3.533333',
    population: '',
  },
  {
    city: 'Ashton-under-Lyne',
    admin: 'Tameside',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '53.5',
    lng: '-2.1',
    population: '',
  },
  {
    city: 'Winchester',
    admin: 'Hampshire',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '51.016667',
    lng: '-1.316667',
    population: '',
  },
  {
    city: 'Sandbach',
    admin: 'Cheshire East',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '53.133333',
    lng: '-2.366667',
    population: '',
  },
  {
    city: 'Derby',
    admin: 'Derby',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '52.933333',
    lng: '-1.5',
    population: '',
  },
  {
    city: 'Twickenham',
    admin: 'Richmond upon Thames',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '51.433333',
    lng: '-0.316667',
    population: '',
  },
  {
    city: 'Saint Helens',
    admin: 'St. Helens',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '53.45',
    lng: '-2.733333',
    population: '',
  },
  {
    city: 'Bury',
    admin: 'Bury',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '53.6',
    lng: '-2.3',
    population: '',
  },
  {
    city: 'Maidenhead',
    admin: 'Windsor and Maidenhead',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '51.516667',
    lng: '-0.7',
    population: '',
  },
  {
    city: 'Wembley',
    admin: 'Brent',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '51.55',
    lng: '-0.283333',
    population: '',
  },
  {
    city: 'Hartlepool',
    admin: 'Hartlepool',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '54.686111',
    lng: '-1.2125',
    population: '',
  },
  {
    city: 'Hugh Town',
    admin: 'Isles of Scilly',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '49.914597',
    lng: '-6.314273',
    population: '',
  },
  {
    city: 'Oldham',
    admin: 'Oldham',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '53.55',
    lng: '-2.116667',
    population: '',
  },
  {
    city: 'Bexleyheath',
    admin: 'Bexley',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '51.45',
    lng: '0.15',
    population: '',
  },
  {
    city: 'Ebbw Vale',
    admin: 'Blaenau Gwent',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '51.783333',
    lng: '-3.2',
    population: '',
  },
  {
    city: 'Magherafelt',
    admin: 'Mid Ulster',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '54.75426',
    lng: '-6.60941',
    population: '',
  },
  {
    city: 'Wigan',
    admin: 'Wigan',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '53.533333',
    lng: '-2.616667',
    population: '',
  },
  {
    city: 'Ballymena',
    admin: 'Mid and East Antrim',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '54.86121',
    lng: '-6.27633',
    population: '',
  },
  {
    city: 'Halifax',
    admin: 'Calderdale',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '53.716667',
    lng: '-1.85',
    population: '',
  },
  {
    city: 'Stockport',
    admin: 'Stockport',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '53.4',
    lng: '-2.15',
    population: '',
  },
  {
    city: 'Stockton-on-Tees',
    admin: 'Stockton-on-Tees',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '54.583333',
    lng: '-1.416667',
    population: '',
  },
  {
    city: 'Northampton',
    admin: 'Northamptonshire',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '52.25',
    lng: '-0.883333',
    population: '',
  },
  {
    city: 'Grays',
    admin: 'Thurrock',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '51.483333',
    lng: '0.333333',
    population: '',
  },
  {
    city: 'Ystrad Mynach',
    admin: 'Caerphilly',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '51.640278',
    lng: '-3.243333',
    population: '',
  },
  {
    city: 'Aberaeron',
    admin: 'Ceredigion',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '52.25',
    lng: '-4.25',
    population: '',
  },
  {
    city: 'Newtown Saint Boswells',
    admin: 'Scottish Borders, The',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '55.583333',
    lng: '-2.683333',
    population: '',
  },
  {
    city: 'Enfield',
    admin: 'Enfield',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '51.666667',
    lng: '-0.066667',
    population: '',
  },
  {
    city: 'Stoke-on-Trent',
    admin: 'Stoke-on-Trent',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '53.0',
    lng: '-2.183333',
    population: '',
  },
  {
    city: 'Sutton',
    admin: 'Sutton',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '51.35',
    lng: '-0.2',
    population: '',
  },
  {
    city: 'Dudley',
    admin: 'Dudley',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '52.5',
    lng: '-2.083333',
    population: '',
  },
  {
    city: 'Wrecsam',
    admin: 'Wrexham',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '53.05',
    lng: '-3.0',
    population: '',
  },
  {
    city: 'Aberdeen',
    admin: 'Aberdeen City',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '57.133333',
    lng: '-2.1',
    population: '',
  },
  {
    city: 'Bolton',
    admin: 'Bolton',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '53.583333',
    lng: '-2.433333',
    population: '',
  },
  {
    city: 'Warrington',
    admin: 'Warrington',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '53.383333',
    lng: '-2.6',
    population: '',
  },
  {
    city: 'Salford',
    admin: 'Salford',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '53.483333',
    lng: '-2.266667',
    population: '',
  },
  {
    city: 'Kensington',
    admin: 'Kensington and Chelsea',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '51.504699',
    lng: '-0.199827',
    population: '',
  },
  {
    city: 'Doncaster',
    admin: 'Doncaster',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '53.533333',
    lng: '-1.116667',
    population: '',
  },
  {
    city: 'Swindon',
    admin: 'Swindon',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '51.516667',
    lng: '-1.783333',
    population: '',
  },
  {
    city: 'Pen-y-Bont ar Ogwr',
    admin: 'Bridgend',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '51.505833',
    lng: '-3.577222',
    population: '',
  },
  {
    city: 'Catford',
    admin: 'Lewisham',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '51.45',
    lng: '-0.016667',
    population: '',
  },
  {
    city: 'Coleraine',
    admin: 'Causeway Coast and Glens',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '55.13489',
    lng: '-6.66873',
    population: '',
  },
  {
    city: 'Barnsley',
    admin: 'Barnsley',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '53.55',
    lng: '-1.483333',
    population: '',
  },
  {
    city: 'Caerdydd',
    admin: 'Cardiff',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '51.5',
    lng: '-3.2',
    population: '',
  },
  {
    city: 'Poole',
    admin: 'Poole',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '50.716667',
    lng: '-2.0',
    population: '',
  },
  {
    city: 'Bracknell',
    admin: 'Bracknell Forest',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '51.416667',
    lng: '-0.75',
    population: '',
  },
  {
    city: 'Wakefield',
    admin: 'Wakefield',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '53.7',
    lng: '-1.483333',
    population: '',
  },
  {
    city: 'Thornbury',
    admin: 'South Gloucestershire',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '51.608889',
    lng: '-2.520278',
    population: '',
  },
  {
    city: 'Wokingham',
    admin: 'Wokingham',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '51.416667',
    lng: '-0.833333',
    population: '',
  },
  {
    city: 'Falkirk',
    admin: 'Falkirk',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '56.0',
    lng: '-3.766667',
    population: '',
  },
  {
    city: 'Haddington',
    admin: 'East Lothian',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '55.933333',
    lng: '-2.766667',
    population: '',
  },
  {
    city: 'Abertawe',
    admin: 'Swansea',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '51.633333',
    lng: '-3.966667',
    population: '',
  },
  {
    city: 'Beverley',
    admin: 'East Riding of Yorkshire',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '53.833333',
    lng: '-0.416667',
    population: '',
  },
  {
    city: 'Croydon',
    admin: 'Croydon',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '51.383333',
    lng: '-0.1',
    population: '',
  },
  {
    city: 'South Shields',
    admin: 'South Tyneside',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '54.987778',
    lng: '-1.421389',
    population: '',
  },
  {
    city: 'Morden',
    admin: 'Merton',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '51.398217',
    lng: '-0.19837',
    population: '',
  },
  {
    city: 'Lochgilphead',
    admin: 'Argyll and Bute',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '56.033333',
    lng: '-5.416667',
    population: '',
  },
  {
    city: 'Worcester',
    admin: 'Worcestershire',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '52.2',
    lng: '-2.2',
    population: '',
  },
  {
    city: 'Matlock',
    admin: 'Derbyshire',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '53.133333',
    lng: '-1.533333',
    population: '',
  },
  {
    city: 'Shrewsbury',
    admin: 'Shropshire',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '52.716667',
    lng: '-2.733333',
    population: '',
  },
  {
    city: 'Truro',
    admin: 'Cornwall',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '50.261667',
    lng: '-5.043333',
    population: '',
  },
  {
    city: 'Hereford',
    admin: 'Herefordshire',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '52.05',
    lng: '-2.716667',
    population: '',
  },
  {
    city: 'Newport',
    admin: 'Newport',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '51.583333',
    lng: '-2.983333',
    population: '',
  },
  {
    city: 'Oakham',
    admin: 'Rutland',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '52.666667',
    lng: '-0.733333',
    population: '',
  },
  {
    city: 'Milton Keynes',
    admin: 'Milton Keynes',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '52.033333',
    lng: '-0.7',
    population: '',
  },
  {
    city: 'Dagenham',
    admin: 'Barking and Dagenham',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '51.55',
    lng: '0.166667',
    population: '',
  },
  {
    city: 'Conwy',
    admin: 'Conwy',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '53.283333',
    lng: '-3.833333',
    population: '',
  },
  {
    city: 'Dalkeith',
    admin: 'Midlothian',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '55.866667',
    lng: '-3.066667',
    population: '',
  },
  {
    city: 'Enniskillen',
    admin: 'Fermanagh and Omagh',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '54.3466',
    lng: '-7.64114',
    population: '',
  },
  {
    city: 'Hamilton',
    admin: 'South Lanarkshire',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '55.766667',
    lng: '-4.033333',
    population: '',
  },
  {
    city: 'Hendon',
    admin: 'Barnet',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '51.6',
    lng: '-0.216667',
    population: '',
  },
  {
    city: 'Hammersmith',
    admin: 'Hammersmith and Fulham',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '51.5',
    lng: '-0.233333',
    population: '',
  },
  {
    city: 'Bromley',
    admin: 'Bromley',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '51.4',
    lng: '0.05',
    population: '',
  },
  {
    city: 'Telford',
    admin: 'Telford and Wrekin',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '52.633333',
    lng: '-2.5',
    population: '',
  },
  {
    city: 'Harrow',
    admin: 'Harrow',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '51.583333',
    lng: '-0.316667',
    population: '',
  },
  {
    city: 'Ealing',
    admin: 'Ealing',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '51.488802',
    lng: '-0.30479',
    population: '',
  },
  {
    city: 'Slough',
    admin: 'Slough',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '51.5',
    lng: '-0.583333',
    population: '',
  },
  {
    city: 'Wolverhampton',
    admin: 'Wolverhampton',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '52.583333',
    lng: '-2.133333',
    population: '',
  },
  {
    city: 'Dumbarton',
    admin: 'West Dunbartonshire',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '55.95',
    lng: '-4.566667',
    population: '',
  },
  {
    city: 'Bangor',
    admin: 'Ards and North Down',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '54.66166',
    lng: '-5.66545',
    population: '',
  },
  {
    city: 'Wallsend',
    admin: 'North Tyneside',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '54.991389',
    lng: '-1.559722',
    population: '',
  },
  {
    city: 'Strabane',
    admin: 'Derry and Strabane',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '54.8224',
    lng: '-7.46844',
    population: '',
  },
  {
    city: 'City of Westminster',
    admin: 'Westminster',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '51.5',
    lng: '-0.116667',
    population: '',
  },
  {
    city: 'Lincoln',
    admin: 'Lincolnshire',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '53.233333',
    lng: '-0.533333',
    population: '',
  },
  {
    city: 'Newport',
    admin: 'Isle of Wight',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '50.7',
    lng: '-1.3',
    population: '',
  },
  {
    city: 'Lisburn',
    admin: 'Lisburn and Castlereagh',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '54.50991',
    lng: '-6.0404',
    population: '',
  },
  {
    city: 'Aylesbury',
    admin: 'Buckinghamshire',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '51.816667',
    lng: '-0.8',
    population: '',
  },
  {
    city: 'Wallasey',
    admin: 'Wirral',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '53.433333',
    lng: '-3.066667',
    population: '',
  },
  {
    city: 'Grimsby',
    admin: 'North East Lincolnshire',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '53.533333',
    lng: '-0.05',
    population: '',
  },
  {
    city: 'Kilmarnock',
    admin: 'East Ayrshire',
    country: 'United Kingdom',
    population_proper: '',
    iso2: 'GB',
    capital: 'admin',
    lat: '55.633333',
    lng: '-4.533333',
    population: '',
  },
];
